package com.coolway.entity;

import java.util.Date;

public class ApplyOpenCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_open_company.id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_open_company.company_name
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_open_company.city_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_open_company.area_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_open_company.email
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_open_company.create_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_open_company.modify_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_open_company.id
     *
     * @return the value of apply_open_company.id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_open_company.id
     *
     * @param id the value for apply_open_company.id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_open_company.company_name
     *
     * @return the value of apply_open_company.company_name
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_open_company.company_name
     *
     * @param companyName the value for apply_open_company.company_name
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_open_company.city_id
     *
     * @return the value of apply_open_company.city_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_open_company.city_id
     *
     * @param cityId the value for apply_open_company.city_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_open_company.area_id
     *
     * @return the value of apply_open_company.area_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_open_company.area_id
     *
     * @param areaId the value for apply_open_company.area_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_open_company.email
     *
     * @return the value of apply_open_company.email
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_open_company.email
     *
     * @param email the value for apply_open_company.email
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_open_company.create_time
     *
     * @return the value of apply_open_company.create_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_open_company.create_time
     *
     * @param createTime the value for apply_open_company.create_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_open_company.modify_time
     *
     * @return the value of apply_open_company.modify_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_open_company.modify_time
     *
     * @param modifyTime the value for apply_open_company.modify_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}