package com.coolway.entity;

import java.util.Date;

public class CompanyUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_user.id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_user.company_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_user.user_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_user.number
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_user.type
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_user.status
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_user.create_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_user.modify_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_user.id
     *
     * @return the value of company_user.id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_user.id
     *
     * @param id the value for company_user.id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_user.company_id
     *
     * @return the value of company_user.company_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_user.company_id
     *
     * @param companyId the value for company_user.company_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_user.user_id
     *
     * @return the value of company_user.user_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_user.user_id
     *
     * @param userId the value for company_user.user_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_user.number
     *
     * @return the value of company_user.number
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_user.number
     *
     * @param number the value for company_user.number
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_user.type
     *
     * @return the value of company_user.type
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_user.type
     *
     * @param type the value for company_user.type
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_user.status
     *
     * @return the value of company_user.status
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_user.status
     *
     * @param status the value for company_user.status
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_user.create_time
     *
     * @return the value of company_user.create_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_user.create_time
     *
     * @param createTime the value for company_user.create_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_user.modify_time
     *
     * @return the value of company_user.modify_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_user.modify_time
     *
     * @param modifyTime the value for company_user.modify_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}