package com.coolway.entity;

import java.util.Date;

public class Company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.city_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.area_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.name
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.emailSuffix
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String emailsuffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.image
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.create_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.modify_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.id
     *
     * @return the value of company.id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.id
     *
     * @param id the value for company.id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.city_id
     *
     * @return the value of company.city_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.city_id
     *
     * @param cityId the value for company.city_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.area_id
     *
     * @return the value of company.area_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.area_id
     *
     * @param areaId the value for company.area_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.name
     *
     * @return the value of company.name
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.name
     *
     * @param name the value for company.name
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.emailSuffix
     *
     * @return the value of company.emailSuffix
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getEmailsuffix() {
        return emailsuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.emailSuffix
     *
     * @param emailsuffix the value for company.emailSuffix
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setEmailsuffix(String emailsuffix) {
        this.emailsuffix = emailsuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.image
     *
     * @return the value of company.image
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.image
     *
     * @param image the value for company.image
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.create_time
     *
     * @return the value of company.create_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.create_time
     *
     * @param createTime the value for company.create_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.modify_time
     *
     * @return the value of company.modify_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.modify_time
     *
     * @param modifyTime the value for company.modify_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}