package com.coolway.entity;

import java.util.Date;

public class Invite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite.id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite.user_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite.invitee
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private String invitee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite.code
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite.status
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite.create_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite.modify_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite.id
     *
     * @return the value of invite.id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite.id
     *
     * @param id the value for invite.id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite.user_id
     *
     * @return the value of invite.user_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite.user_id
     *
     * @param userId the value for invite.user_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite.invitee
     *
     * @return the value of invite.invitee
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public String getInvitee() {
        return invitee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite.invitee
     *
     * @param invitee the value for invite.invitee
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setInvitee(String invitee) {
        this.invitee = invitee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite.code
     *
     * @return the value of invite.code
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite.code
     *
     * @param code the value for invite.code
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite.status
     *
     * @return the value of invite.status
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite.status
     *
     * @param status the value for invite.status
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite.create_time
     *
     * @return the value of invite.create_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite.create_time
     *
     * @param createTime the value for invite.create_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite.modify_time
     *
     * @return the value of invite.modify_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite.modify_time
     *
     * @param modifyTime the value for invite.modify_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}