package com.coolway.entity;

import java.util.Date;

public class Notify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.user_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.type
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.to_user_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer toUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.content
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.status
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.create_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.modify_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.id
     *
     * @return the value of notify.id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.id
     *
     * @param id the value for notify.id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.user_id
     *
     * @return the value of notify.user_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.user_id
     *
     * @param userId the value for notify.user_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.type
     *
     * @return the value of notify.type
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.type
     *
     * @param type the value for notify.type
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.to_user_id
     *
     * @return the value of notify.to_user_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.to_user_id
     *
     * @param toUserId the value for notify.to_user_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setToUserId(Integer toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.content
     *
     * @return the value of notify.content
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.content
     *
     * @param content the value for notify.content
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.status
     *
     * @return the value of notify.status
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.status
     *
     * @param status the value for notify.status
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.create_time
     *
     * @return the value of notify.create_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.create_time
     *
     * @param createTime the value for notify.create_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.modify_time
     *
     * @return the value of notify.modify_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.modify_time
     *
     * @param modifyTime the value for notify.modify_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}