package com.coolway.entity;

import java.util.Date;

public class PostReply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_reply.id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_reply.post_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_reply.user_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_reply.user_name
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_reply.status
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_reply.quote_reply_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer quoteReplyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_reply.create_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_reply.modify_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_reply.content
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_reply.id
     *
     * @return the value of post_reply.id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_reply.id
     *
     * @param id the value for post_reply.id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_reply.post_id
     *
     * @return the value of post_reply.post_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_reply.post_id
     *
     * @param postId the value for post_reply.post_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_reply.user_id
     *
     * @return the value of post_reply.user_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_reply.user_id
     *
     * @param userId the value for post_reply.user_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_reply.user_name
     *
     * @return the value of post_reply.user_name
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_reply.user_name
     *
     * @param userName the value for post_reply.user_name
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_reply.status
     *
     * @return the value of post_reply.status
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_reply.status
     *
     * @param status the value for post_reply.status
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_reply.quote_reply_id
     *
     * @return the value of post_reply.quote_reply_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getQuoteReplyId() {
        return quoteReplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_reply.quote_reply_id
     *
     * @param quoteReplyId the value for post_reply.quote_reply_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setQuoteReplyId(Integer quoteReplyId) {
        this.quoteReplyId = quoteReplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_reply.create_time
     *
     * @return the value of post_reply.create_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_reply.create_time
     *
     * @param createTime the value for post_reply.create_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_reply.modify_time
     *
     * @return the value of post_reply.modify_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_reply.modify_time
     *
     * @param modifyTime the value for post_reply.modify_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_reply.content
     *
     * @return the value of post_reply.content
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_reply.content
     *
     * @param content the value for post_reply.content
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setContent(String content) {
        this.content = content;
    }
}