package com.coolway.entity;

import java.util.Date;

public class Post {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.company_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.category_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.user_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.user_name
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.title
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.status
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.authority
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String authority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.is_top
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.reply_num
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer replyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.favor_num
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Integer favorNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.create_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.modify_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.last_reply_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private Date lastReplyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.content
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.id
     *
     * @return the value of post.id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.id
     *
     * @param id the value for post.id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.company_id
     *
     * @return the value of post.company_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.company_id
     *
     * @param companyId the value for post.company_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.category_id
     *
     * @return the value of post.category_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.category_id
     *
     * @param categoryId the value for post.category_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.user_id
     *
     * @return the value of post.user_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.user_id
     *
     * @param userId the value for post.user_id
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.user_name
     *
     * @return the value of post.user_name
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.user_name
     *
     * @param userName the value for post.user_name
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.title
     *
     * @return the value of post.title
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.title
     *
     * @param title the value for post.title
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.status
     *
     * @return the value of post.status
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.status
     *
     * @param status the value for post.status
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.authority
     *
     * @return the value of post.authority
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.authority
     *
     * @param authority the value for post.authority
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setAuthority(String authority) {
        this.authority = authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.is_top
     *
     * @return the value of post.is_top
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.is_top
     *
     * @param isTop the value for post.is_top
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setIsTop(String isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.reply_num
     *
     * @return the value of post.reply_num
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getReplyNum() {
        return replyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.reply_num
     *
     * @param replyNum the value for post.reply_num
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setReplyNum(Integer replyNum) {
        this.replyNum = replyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.favor_num
     *
     * @return the value of post.favor_num
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Integer getFavorNum() {
        return favorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.favor_num
     *
     * @param favorNum the value for post.favor_num
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setFavorNum(Integer favorNum) {
        this.favorNum = favorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.create_time
     *
     * @return the value of post.create_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.create_time
     *
     * @param createTime the value for post.create_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.modify_time
     *
     * @return the value of post.modify_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.modify_time
     *
     * @param modifyTime the value for post.modify_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.last_reply_time
     *
     * @return the value of post.last_reply_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public Date getLastReplyTime() {
        return lastReplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.last_reply_time
     *
     * @param lastReplyTime the value for post.last_reply_time
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setLastReplyTime(Date lastReplyTime) {
        this.lastReplyTime = lastReplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.content
     *
     * @return the value of post.content
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.content
     *
     * @param content the value for post.content
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    public void setContent(String content) {
        this.content = content;
    }
}