package com.coolway.entity;

import java.util.Date;

public class TopicTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_tag.id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_tag.topic_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Integer topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_tag.tag_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_tag.create_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_tag.modify_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_tag.id
     *
     * @return the value of topic_tag.id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_tag.id
     *
     * @param id the value for topic_tag.id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_tag.topic_id
     *
     * @return the value of topic_tag.topic_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_tag.topic_id
     *
     * @param topicId the value for topic_tag.topic_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_tag.tag_id
     *
     * @return the value of topic_tag.tag_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_tag.tag_id
     *
     * @param tagId the value for topic_tag.tag_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_tag.create_time
     *
     * @return the value of topic_tag.create_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_tag.create_time
     *
     * @param createTime the value for topic_tag.create_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_tag.modify_time
     *
     * @return the value of topic_tag.modify_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_tag.modify_time
     *
     * @param modifyTime the value for topic_tag.modify_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}