package com.coolway.entity;

import java.util.Date;

public class TopicReply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_reply.id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_reply.topic_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Integer topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_reply.user_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_reply.user_name
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_reply.status
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_reply.quote_reply_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Integer quoteReplyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_reply.create_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_reply.modify_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_reply.content
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_reply.id
     *
     * @return the value of topic_reply.id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_reply.id
     *
     * @param id the value for topic_reply.id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_reply.topic_id
     *
     * @return the value of topic_reply.topic_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_reply.topic_id
     *
     * @param topicId the value for topic_reply.topic_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_reply.user_id
     *
     * @return the value of topic_reply.user_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_reply.user_id
     *
     * @param userId the value for topic_reply.user_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_reply.user_name
     *
     * @return the value of topic_reply.user_name
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_reply.user_name
     *
     * @param userName the value for topic_reply.user_name
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_reply.status
     *
     * @return the value of topic_reply.status
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_reply.status
     *
     * @param status the value for topic_reply.status
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_reply.quote_reply_id
     *
     * @return the value of topic_reply.quote_reply_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Integer getQuoteReplyId() {
        return quoteReplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_reply.quote_reply_id
     *
     * @param quoteReplyId the value for topic_reply.quote_reply_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setQuoteReplyId(Integer quoteReplyId) {
        this.quoteReplyId = quoteReplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_reply.create_time
     *
     * @return the value of topic_reply.create_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_reply.create_time
     *
     * @param createTime the value for topic_reply.create_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_reply.modify_time
     *
     * @return the value of topic_reply.modify_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_reply.modify_time
     *
     * @param modifyTime the value for topic_reply.modify_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_reply.content
     *
     * @return the value of topic_reply.content
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_reply.content
     *
     * @param content the value for topic_reply.content
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setContent(String content) {
        this.content = content;
    }
}