package com.coolway.entity;

import java.util.Date;

public class Topic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.company_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.user_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.user_name
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.title
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.status
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.authority
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private String authority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.is_top
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private String isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.reply_num
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Integer replyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.favor_num
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Integer favorNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.create_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.modify_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.last_reply_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private Date lastReplyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.content
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.id
     *
     * @return the value of topic.id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.id
     *
     * @param id the value for topic.id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.company_id
     *
     * @return the value of topic.company_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.company_id
     *
     * @param companyId the value for topic.company_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.user_id
     *
     * @return the value of topic.user_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.user_id
     *
     * @param userId the value for topic.user_id
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.user_name
     *
     * @return the value of topic.user_name
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.user_name
     *
     * @param userName the value for topic.user_name
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.title
     *
     * @return the value of topic.title
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.title
     *
     * @param title the value for topic.title
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.status
     *
     * @return the value of topic.status
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.status
     *
     * @param status the value for topic.status
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.authority
     *
     * @return the value of topic.authority
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.authority
     *
     * @param authority the value for topic.authority
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setAuthority(String authority) {
        this.authority = authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.is_top
     *
     * @return the value of topic.is_top
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public String getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.is_top
     *
     * @param isTop the value for topic.is_top
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setIsTop(String isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.reply_num
     *
     * @return the value of topic.reply_num
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Integer getReplyNum() {
        return replyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.reply_num
     *
     * @param replyNum the value for topic.reply_num
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setReplyNum(Integer replyNum) {
        this.replyNum = replyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.favor_num
     *
     * @return the value of topic.favor_num
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Integer getFavorNum() {
        return favorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.favor_num
     *
     * @param favorNum the value for topic.favor_num
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setFavorNum(Integer favorNum) {
        this.favorNum = favorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.create_time
     *
     * @return the value of topic.create_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.create_time
     *
     * @param createTime the value for topic.create_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.modify_time
     *
     * @return the value of topic.modify_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.modify_time
     *
     * @param modifyTime the value for topic.modify_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.last_reply_time
     *
     * @return the value of topic.last_reply_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public Date getLastReplyTime() {
        return lastReplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.last_reply_time
     *
     * @param lastReplyTime the value for topic.last_reply_time
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setLastReplyTime(Date lastReplyTime) {
        this.lastReplyTime = lastReplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.content
     *
     * @return the value of topic.content
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.content
     *
     * @param content the value for topic.content
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    public void setContent(String content) {
        this.content = content;
    }
}