package com.coolway.dao;

import com.coolway.entity.ApplyOpenCompany;
import com.coolway.entity.ApplyOpenCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplyOpenCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_open_company
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int countByExample(ApplyOpenCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_open_company
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int deleteByExample(ApplyOpenCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_open_company
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_open_company
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int insert(ApplyOpenCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_open_company
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int insertSelective(ApplyOpenCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_open_company
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    List<ApplyOpenCompany> selectByExample(ApplyOpenCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_open_company
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    ApplyOpenCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_open_company
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int updateByExampleSelective(@Param("record") ApplyOpenCompany record, @Param("example") ApplyOpenCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_open_company
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int updateByExample(@Param("record") ApplyOpenCompany record, @Param("example") ApplyOpenCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_open_company
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int updateByPrimaryKeySelective(ApplyOpenCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_open_company
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int updateByPrimaryKey(ApplyOpenCompany record);
}