package com.coolway.dao;

import com.coolway.entity.CompanyUser;
import com.coolway.entity.CompanyUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_user
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int countByExample(CompanyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_user
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int deleteByExample(CompanyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_user
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_user
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int insert(CompanyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_user
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int insertSelective(CompanyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_user
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    List<CompanyUser> selectByExample(CompanyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_user
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    CompanyUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_user
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int updateByExampleSelective(@Param("record") CompanyUser record, @Param("example") CompanyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_user
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int updateByExample(@Param("record") CompanyUser record, @Param("example") CompanyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_user
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int updateByPrimaryKeySelective(CompanyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_user
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int updateByPrimaryKey(CompanyUser record);
}