package com.coolway.dao;

import com.coolway.entity.Notify;
import com.coolway.entity.NotifyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    int countByExample(NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    int deleteByExample(NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    int insert(Notify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    int insertSelective(Notify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    List<Notify> selectByExample(NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    Notify selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    int updateByExampleSelective(@Param("record") Notify record, @Param("example") NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    int updateByExample(@Param("record") Notify record, @Param("example") NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    int updateByPrimaryKeySelective(Notify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbggenerated Thu Sep 20 10:27:02 CST 2012
     */
    int updateByPrimaryKey(Notify record);
}