package com.coolway.dao;

import com.coolway.entity.PostReply;
import com.coolway.entity.PostReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_reply
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int countByExample(PostReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_reply
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int deleteByExample(PostReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_reply
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_reply
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int insert(PostReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_reply
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int insertSelective(PostReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_reply
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    List<PostReply> selectByExampleWithBLOBs(PostReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_reply
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    List<PostReply> selectByExample(PostReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_reply
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    PostReply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_reply
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int updateByExampleSelective(@Param("record") PostReply record, @Param("example") PostReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_reply
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int updateByExampleWithBLOBs(@Param("record") PostReply record, @Param("example") PostReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_reply
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int updateByExample(@Param("record") PostReply record, @Param("example") PostReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_reply
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int updateByPrimaryKeySelective(PostReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_reply
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int updateByPrimaryKeyWithBLOBs(PostReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_reply
     *
     * @mbggenerated Fri Oct 26 11:18:55 CST 2012
     */
    int updateByPrimaryKey(PostReply record);
}